# Generated by Django 5.0.2 on 2024-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_id_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.BigIntegerField(null=True),
        ),
    ]
